//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSString, CYFTextEventListener_, CYFTextEvent_;

@protocol CYFTextEventListenerDelegate_ <NSObject>
- (void)textEventListener:(CYFTextEventListener_ *)arg1 withTextFieldAddressString:(NSString *)arg2;
- (void)textEventListener:(CYFTextEventListener_ *)arg1 withTextData:(CYFTextEvent_ *)arg2;
@end

@interface CYFTextEventListener_ : NSObject
{
    id _currentField;
    long long _textChangeEventAllowedLimit;
    long long _totalTextEventCount;
    long long _previousTextCount;
    NSString *_prevAddress;
}

@property(retain, nonatomic) NSString *prevAddress; // @synthesize prevAddress=_prevAddress;
@property(nonatomic) long long previousTextCount; // @synthesize previousTextCount=_previousTextCount;
@property(nonatomic) long long totalTextEventCount; // @synthesize totalTextEventCount=_totalTextEventCount;
@property(nonatomic) long long textChangeEventAllowedLimit; // @synthesize textChangeEventAllowedLimit=_textChangeEventAllowedLimit;
@property(retain, nonatomic) id currentField; // @synthesize currentField=_currentField;
@property(nonatomic, weak) id <CYFTextEventListenerDelegate_> textEventRecorder; // @synthesize textEventRecorder=_textEventRecorder;

- (_Bool)isCurrentEventCopyPaste:(id)arg1 noOfChar:(long long)arg2 withEventType:(unsigned long long)arg3;
- (void)enqueueTextDataOfField:(id)arg1 withEventType:(unsigned long long)arg2;
- (void)textWidgetTextDidEndEditing:(id)arg1;
- (void)textWidgetTextDidChange:(id)arg1;
- (void)textWidgetTextDidBeginEditing:(id)arg1;
- (long long)getTextChangeEventCount;
- (long long)getTotalTextEventCount;
- (void)configureTextEventNotifications;
- (void)dealloc;
- (id)initWithEventRecorder:(id)arg1;
- (id)init;

@end

