//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface CYFBackgroundEvent_ : NSObject
{
    unsigned long long _eventType;
    long long _timeStamp;
}

@property(nonatomic) long long timeStamp; // @synthesize timeStamp=_timeStamp;
@property(nonatomic) unsigned long long eventType; // @synthesize eventType=_eventType;
- (instancetype)initWithEventType:(unsigned long long)arg1 andTimeStamp:(id)arg2;

@end

