//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


#import <Foundation/Foundation.h>

@class CYFMotionModel_, NSDate, NSMutableArray;

@interface CYFMotionHandler_ : NSObject
{
    NSMutableArray *_phaseOneEvents;
    NSMutableArray *_phaseTwoEvents;
    NSMutableArray *_phaseThreeEvents;
    NSDate *_lastPhase3EventTime;
    CYFMotionModel_ *_lastMotionOb;
    long long _totalEvents;
}

@property(nonatomic) long long totalEvents; // @synthesize totalEvents=_totalEvents;
@property(retain, nonatomic) CYFMotionModel_ *lastMotionOb; // @synthesize lastMotionOb=_lastMotionOb;
@property(retain, nonatomic) NSDate *lastPhase3EventTime; // @synthesize lastPhase3EventTime=_lastPhase3EventTime;
@property(retain) NSMutableArray *phaseThreeEvents; // @synthesize phaseThreeEvents=_phaseThreeEvents;
@property(retain) NSMutableArray *phaseTwoEvents; // @synthesize phaseTwoEvents=_phaseTwoEvents;
@property(retain) NSMutableArray *phaseOneEvents; // @synthesize phaseOneEvents=_phaseOneEvents;

- (id)formatEvent:(id)arg1 timeStamp:(long long)arg2 andTrigger:(_Bool)arg3;
- (void)autoPostSensorDataForMotionEvent;
- (double)getMotionDelta:(id)arg1;
- (id)createMotionModel:(id)arg1;
- (void)updateData:(id)arg1 timeStamp:(id)arg2 andTrigger:(_Bool)arg3;
- (long long)getTotalEventCount;
- (id)getSensorData;
- (void)reset;
- (void)create;
- (void)dealloc;
- (id)init;

@end

