//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


#import <Foundation/Foundation.h>

@class CYFMotionModel_;

@interface CYFMotionModelDelta_ : NSObject
{
    CYFMotionModel_ *_model;
    double _delta;
}

@property(nonatomic) double delta; // @synthesize delta=_delta;
@property(retain, nonatomic) CYFMotionModel_ *model; // @synthesize model=_model;


@end

