//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSDate;

@interface CYFOriModel_ : NSObject
{
    _Bool _touch;
    double _pitch;
    double _roll;
    double _yaw;
    NSDate *_timestamp;
}

@property(nonatomic) _Bool touch; // @synthesize touch=_touch;
@property(retain, nonatomic) NSDate *timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic) double yaw; // @synthesize yaw=_yaw;
@property(nonatomic) double roll; // @synthesize roll=_roll;
@property(nonatomic) double pitch; // @synthesize pitch=_pitch;

@end

